### ISSUE TITLE
[Q] taiga-async shuts down without any error

### ISSUE THREAD

**Issue by gingerbreadassassin** [taigaio/taiga-back#75]
I am trying to run taiga on a docker swarm host behind traefik. Here are the contents of my stack file sanitized:

```yaml
version: '3.9'

# Adapted from https://github.com/kaleidos-ventures/taiga-docker/blob/main/docker-compose.yml

x-environment:
  &default-back-environment
  # Database settings
  POSTGRES_DB: "taiga"
  POSTGRES_USER: "taiga"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_HOST: "taiga-db"
  # Taiga settings
  TAIGA_SECRET_KEY: "${TAIGA_SECRET}"
  TAIGA_SITES_SCHEME: "https"
  TAIGA_SITES_DOMAIN: "taiga.mydomain.tld"
  TAIGA_SUBPATH: ""
  RABBITMQ_USER: "taiga"
  RABBITMQ_PASS: "${RABBIT_PASSWORD}"
  # Telemetry settings
  ENABLE_TELEMETRY: "False"

x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media

services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - taiga-db-data:/var/lib/postgresql/data

  taiga-back:
    image: taigaio/taiga-back:${VERSION}
    environment:
        <<: *default-back-environment
        ENABLE_GITLAB_AUTH: "True"
        GITLAB_API_CLIENT_ID: "${GITLAB_APP_ID}"
        GITLAB_API_CLIENT_SECRET: "${GITLAB_SECRET}"
        GITLAB_URL: "https://git.mydomain.tld"
        PUBLIC_REGISTER_ENABLED: "True"
    volumes: *default-back-volumes

  taiga-async:
    image: taigaio/taiga-back:${VERSION}
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: 
      <<: *default-back-environment
    volumes: *default-back-volumes

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}"
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq

  taiga-front:
    image: taigaio/taiga-front:${VERSION}
    environment:
      TAIGA_URL: "https://taiga.mydomain.tld"
      TAIGA_WEBSOCKETS_URL: "wss://taiga.mydomain.tld"
      TAIGA_SUBPATH: ""
      ENABLE_GITLAB_AUTH: "true"
      GITLAB_API_CLIENT_ID: "${GITLAB_APP_ID}"
      GITLAB_URL: "https://git.mydomain.tld"
      PUBLIC_REGISTER_ENABLED: "true"

  taiga-events:
    image: taigaio/taiga-events:${VERSION}
    environment:
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: "${RABBIT_PASSWORD}"
      TAIGA_SECRET_KEY: "${TAIGA_SECRET}"

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: "${RABBIT_PASSWORD}"
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq

  taiga-protected:
    image: taigaio/taiga-protected:${VERSION}
    environment:
      MAX_AGE: 360
      SECRET_KEY: "${TAIGA_SECRET}"

  taiga-gateway:
    image: taiga-nginx:1.19-alpine
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=webgateway"
        - "traefik.http.routers.$CI_PROJECT_NAME$BRANCH_LABEL.rule=Host(`taiga.mydomain.tld`)"
        - "traefik.http.routers.$CI_PROJECT_NAME$BRANCH_LABEL.entrypoints=websecure"
        - "traefik.http.routers.$CI_PROJECT_NAME$BRANCH_LABEL.tls=true"
        - "traefik.http.routers.$CI_PROJECT_NAME$BRANCH_LABEL.tls.certresolver=le"
        - "traefik.http.routers.$CI_PROJECT_NAME$BRANCH_LABEL.service=$CI_PROJECT_NAME$BRANCH_LABEL"
        - "traefik.http.services.$CI_PROJECT_NAME$BRANCH_LABEL.loadbalancer.server.port=80"
        - "traefik.http.services.$CI_PROJECT_NAME$BRANCH_LABEL.loadbalancer.server.scheme=http"
    volumes:
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    networks:
      default:
      webgateway:

networks:
  webgateway:
    external: true

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:
```

The taiga-async service keeps restarting, non-zero exit:

```
[connor@bigdell ~]$ docker stack ps devtools-taiga
ID             NAME                                     IMAGE                            NODE      DESIRED STATE   CURRENT STATE           ERROR                       PORTS
w8khtis2gm1b   devtools-taiga_taiga-async-rabbitmq.1    rabbitmq:3.8-management-alpine   bigdell   Running         Running 4 minutes ago
mcyotg9pvunl   devtools-taiga_taiga-async.1             taigaio/taiga-back:6.4.0         bigdell   Running         Running 1 second ago
pnau5og8fab1    \_ devtools-taiga_taiga-async.1         taigaio/taiga-back:6.4.0         bigdell   Shutdown        Failed 7 seconds ago    "task: non-zero exit (1)"
azu6bl4eqm2o    \_ devtools-taiga_taiga-async.1         taigaio/taiga-back:6.4.0         bigdell   Shutdown        Failed 19 seconds ago   "task: non-zero exit (1)"
ly7r2x3c65qn    \_ devtools-taiga_taiga-async.1         taigaio/taiga-back:6.4.0         bigdell   Shutdown        Failed 31 seconds ago   "task: non-zero exit (1)"
wlui3m2hh2e3    \_ devtools-taiga_taiga-async.1         taigaio/taiga-back:6.4.0         bigdell   Shutdown        Failed 43 seconds ago   "task: non-zero exit (1)"
swwo0y8nwfiw   devtools-taiga_taiga-back.1              taigaio/taiga-back:6.4.0         bigdell   Running         Running 4 minutes ago
yg6lha8qif6r   devtools-taiga_taiga-db.1                postgres:12.3                    bigdell   Running         Running 4 minutes ago
to9pjiwoikwg   devtools-taiga_taiga-events-rabbitmq.1   rabbitmq:3.8-management-alpine   bigdell   Running         Running 4 minutes ago
jbc5pbytstx7   devtools-taiga_taiga-events.1            taigaio/taiga-events:6.4.0       bigdell   Running         Running 4 minutes ago
sy1qjd3b57ml   devtools-taiga_taiga-front.1             taigaio/taiga-front:6.4.0        bigdell   Running         Running 4 minutes ago
dkh21ros1lsx   devtools-taiga_taiga-gateway.1           taiga-nginx:1.19-alpine          bigdell   Running         Running 4 minutes ago
wf3qlb50w8kr    \_ devtools-taiga_taiga-gateway.1       taiga-nginx:1.19-alpine          bigdell   Shutdown        Failed 4 minutes ago    "task: non-zero exit (1)"
uwquy9crzy63   devtools-taiga_taiga-protected.1         taigaio/taiga-protected:6.4.0    bigdell   Running         Running 4 minutes ago
```

There's no error message, or anything helpful in DEBUG:

```
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | Give permission to taiga:taiga
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | Starting Celery...
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |  -------------- celery@9f3cdc50dde7 v4.3.0 (rhubarb)
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | ---- **** -----
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | --- * ***  * -- Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-debian-10.9 2022-01-21 22:35:03
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | -- * - **** ---
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | - ** ---------- [config]
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | - ** ---------- .> app:         taiga:0x7f0558c0f250
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | - ** ---------- .> transport:   amqp://taiga:**@taiga-async-rabbitmq:5672/taiga
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | - ** ---------- .> results:     disabled://
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | - *** --- * --- .> concurrency: 4 (prefork)
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | -- ******* ---- .> task events: ON
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | --- ***** -----
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |  -------------- [queues]
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |                 .> tasks            exchange=tasks(topic) key=task.default
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | [tasks]
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . celery.accumulate
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . celery.backend_cleanup
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . celery.chain
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . celery.chord
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . celery.chord_unlock
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . celery.chunks
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . celery.group
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . celery.map
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . celery.starmap
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . djmail.tasks.retry_send_messages
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . djmail.tasks.send_messages
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.auth.token_denylist.tasks.flush_expired_tokens
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.export_import.tasks.delete_project_dump
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.export_import.tasks.dump_project
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.export_import.tasks.load_project_dump
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.projects.contact.services.send_contact_email
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.projects.notifications.tasks.send_bulk_email
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.projects.services.projects.delete_project
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.projects.services.projects.delete_projects
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.projects.userstories.services._async_tasks_after_backlog_or_sprint_order_change
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.projects.userstories.services._async_tasks_after_kanban_order_change
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.telemetry.tasks.send_telemetry
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.timeline.service.push_to_timelines
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.webhooks.tasks.change_webhook
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.webhooks.tasks.create_webhook
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.webhooks.tasks.delete_webhook
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.webhooks.tasks.resend_webhook
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |   . taiga.webhooks.tasks.test_webhook
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    |
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | [2022-01-21 22:35:04,666: INFO/MainProcess] beat: Shutting down...
devtools-taiga_taiga-async.1.k6ay984zgzfq@bigdell    | [2022-01-21 22:35:04,667: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
```

These lines just repeat when following the logs via `docker service logs`

Here are the environment variables from the spawned container:
```
PATH=/opt/venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=4dc53944b7f3
ENABLE_TELEMETRY=False
POSTGRES_DB=taiga
POSTGRES_HOST=taiga-db
POSTGRES_PASSWORD=-private-
POSTGRES_USER=taiga
RABBITMQ_PASS=-private-
RABBITMQ_USER=taiga
TAIGA_SECRET_KEY=-private-
TAIGA_SITES_DOMAIN=taiga.mydomain.tld
TAIGA_SITES_SCHEME=https
TAIGA_SUBPATH=
LANG=C.UTF-8
GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
PYTHON_VERSION=3.7.10
PYTHON_PIP_VERSION=21.0.1
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/29f37dbe6b3842ccd52d61816a3044173962ebeb/public/get-pip.py
PYTHON_GET_PIP_SHA256=e03eb8a33d3b441ff484c56a436ff10680479d4bd14e59268e67977ed40904de
DEBIAN_FRONTEND=noninteractive
PYTHONUNBUFFERED=1
PYTHONDONTWRITEBYTECODE=1
PYTHONFAULTHANDLER=1
GOSU_VERSION=1.12
DJANGO_SETTINGS_MODULE=settings.config
HOME=/root
```

Note that I am using gitlab to deploy this to my swarm, and to work around deploying via a gitlab runner, I build nginx to copy the [config](https://github.com/kaleidos-ventures/taiga-docker/blob/main/taiga-gateway/taiga.conf) to the image. I'm using version 6.4.0.

**Comment by gingerbreadassassin** [comment]
On a hunch, I took a look at the logs for taiga-async-rabbitmq:

```
devtools-taiga_taiga-async-rabbitmq.1.qsd2t4ashjpe@bigdell    | AMQPLAIN login refused: user 'taiga' - invalid credentials
devtools-taiga_taiga-async-rabbitmq.1.qsd2t4ashjpe@bigdell    | 2022-01-21 23:11:39.318 [info] <0.1275.0> closing AMQP connection <0.1275.0> (10.0.22.4:43356 -> 10.0.22.14:5672)
devtools-taiga_taiga-async-rabbitmq.1.qsd2t4ashjpe@bigdell    | 2022-01-21 23:11:39.318 [info] <0.1277.0> Closing all channels from connection '10.0.22.4:43356 -> 10.0.22.14:5672' because it has been closed
```

After double-checking my stack file, I found an errant `"`

```
  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}"  <-----
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq 
 ```


After removing this,  the stack is up and running, (though taiga was reachable already). A little frustrating, as there was no mention of an authentication failure on the affected service, but putting this here for anyone else who might be having the same trouble.
